### ISSUE TITLE
support JSON syntax

### ISSUE THREAD

**Issue by snarfed** [snarfed/wordpress-micropub#25]
https://www.w3.org/TR/micropub/#json-syntax

e.g.

```json
{
  "type": ["h-entry"],
  "properties": {
    "content": ["hello world"],
    "category": ["foo","bar"],
    "photo": ["https://photos.example.com/592829482876343254.jpg"]
  }
}
```

**Comment by dshanske** [comment]
I think the best way to do this is to create a shim for form handling that converts into an array that matches the JSON syntax. Then we can use the same handler for both.  Thoughts?

**Comment by snarfed** [comment]
agreed!

having said that, POSSE doesn't require this, so it's probably not a priority for you right now...? just checking.

**Comment by dshanske** [comment]
If I read the standard correctly, all the queries require a return in JSON now. All error responses also require a JSON return. So in order to support POSSE, I would have to create a function to return JSON, which should include a function for returning the error responses. 

Either way, a change of that magnitude means the other pieces need to change, which means I might build something only to have to tear it down, which isn't good in the long term.

So what I want to do is do some of the general separation and then work on the syndication target part. So, move the form handling out of parse_query into its own function and make parse_query only handle authentication. Move the request_query function to be called directly from parse_query instead of further down after it is already looking at $_POST. That will separate queries and posting at the high level. 

Then I can work on changing queries over to JSON error and return support, including syndicate-to. JSON for Posting is a separate issue...

**Comment by snarfed** [comment]
ah, sorry, i was unclear. i only meant JSON input here originally, not output...but you're right, we do want JSON output eventually too. sgtm.

honestly, JSON input and output shouldn't be too big a deal. converting JSON input to array like you mentioned, and outputting JSON as you go, both results and errors, should be straightforward and not invasive changes. don't worry too much!

btw:

> I might build something only to have to tear it down, which isn't good in the long term.

not at all! _build one to throw away_ is a time honored software engineering practice. you often learn critical information while building something the first time that you couldn't learn any other way. prototyping is basically doing this intentionally. you can sometimes somewhat avoid it with doing agile/incremental, but not always. http://c2.com/cgi/wiki?PlanToThrowOneAway

**Comment by dshanske** [comment]
I rebuild things all the time. Look at the changes that I made from post processing to pre processing. I just don't want to build something that I know will not fit the needs I know we'll have in future if I can plan for them.

**Comment by dshanske** [comment]
I admit to being a worrier. But I will try to add things in pieces so they can be reviewed.

**Comment by snarfed** [comment]
sounds good. thank you! and with tests please! :P

**Comment by snarfed** [comment]
this is pretty much done! some features are still remaining, but they're orthogonal to JSON syntax.

happy publishing!
