### ISSUE TITLE
Published date parsing error

### ISSUE THREAD

**Issue by dshanske** [snarfed/wordpress-micropub#74]
I recently posted for the first time with Micropub + OwnYourGram. The date appeared as 1969.

**Comment by dshanske** [comment]
Related? https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/87

**Comment by dshanske** [comment]
In this, after exploration, I changed it so if it can't parse the published date, it would default to now.

**Comment by snarfed** [comment]
huh. that's surprising, since wordpress-micropub [accepts and uses the `published` param](https://github.com/snarfed/wordpress-micropub/blob/1754499aaa83e61b16d19564042aece5ca7acd48/micropub.php#L478), which [ownyourgram claims it sends](https://ownyourgram.com/docs#micropub). cc @aaronpk to make sure that's true.

@dshanske, are you able to reproduce this?

**Comment by dshanske** [comment]
I will try again

**Comment by dshanske** [comment]
Addressed with latest pr
